package db.entities;

public enum MaterialType {
    TRAIT_ARMOR,
    TRAIT_WEAPON,
    TRAIT_JEWELRY,
    BASE_CLOTH,
    BASE_LEATHER,
    BASE_METAL,
    BASE_JEWELRY,
    BASE_WOOD,
    FINE_CLOTHING,
    RARE_CLOTHING,
    EPIC_CLOTHING,
    LEGENDARY_CLOTHING,
    FINE_SMITHING,
    RARE_SMITHING,
    EPIC_SMITHING,
    LEGENDARY_SMITHING,
    FINE_JEWELRY,
    RARE_JEWELRY,
    EPIC_JEWELRY,
    LEGENDARY_JEWELRY,
    FINE_WOODWORK,
    RARE_WOODWORK,
    EPIC_WOODWORK,
    LEGENDARY_WOODWORK
}
